#!/bin/bash

set -e

if [ $CI ]; then
  echo "pre-commit: CI detected, updating lock files before commit"

  npm run clean -- --yes
  npm run bootstrap -- --no-ci --package-lock-only --ignore-scripts
  git add packages/*/package-lock.json
fi
