#!/bin/bash

set -e

TRAVIS_BRANCH="${TRAVIS_BRANCH:-not-master}"
TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG:-not-theforeman}"

if [ $CI ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_REPO_SLUG == 'theforeman/foreman-js' ]; then
  echo "pre-commit: CI detected, updating lock files before commit"

  npm run clean -- --yes
  npm run bootstrap -- --no-ci --package-lock-only --ignore-scripts
  git add packages/*/package-lock.json
fi
