name: foreman-js ci
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    continue-on-error: true
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install foreman-js npm dependencies
        run: npm install
      - name: Build foreman-js
        run: npm run build
      - name: Run foreman-js commit linter
        if: ${{ always() }}
        uses: wagoid/commitlint-github-action@v1
        with:
          configFile: .commitlintrc.json
      - name: Run foreman-js lint
        if: ${{ always() }}
        run: npm run lint
      - name: Run foreman-js test
        if: ${{ always() }}
        run: npm run test

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: foreman
            org: theforeman
          - repo: katello
            org: Katello
          - repo: foreman-tasks
            org: theforeman
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          path: ./projects/foreman-js
      - name: Install foreman-js npm dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/projects/foreman-js
      - name: Checkout foreman
        uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          path: ./projects/foreman
      - name: Install foreman npm dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/projects/foreman
      - name: Link foreman to foreman-js
        run: npm run foreman-js:link
        working-directory: ${{ github.workspace }}/projects/foreman
      - name: Checkout ${{ matrix.repo }}
        if: ${{ matrix.repo != 'foreman' }}
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.org }}/${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: ./projects/${{ matrix.repo }}
      - name: Install ${{ matrix.repo }} npm dependencies
        if: ${{ matrix.repo != 'foreman' }}
        run: npm install
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
      - name: Link ${{ matrix.repo }} to foreman-js
        if: ${{ matrix.repo == 'foreman-tasks' }}
        run: npm run foreman-js:link
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
      - name: Run ${{ matrix.repo }} tests
        run: npm test
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
      - name: Run ${{ matrix.repo }} lint
        run: npm run lint
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
