name: Test foreman plugins with foreman-js
on: [push, pull_request, workflow_dispatch]

env:
  BUNDLE_WITHOUT: "console:development:journald:libvirt"


jobs:
  test-plugins:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: katello
            org: Katello
            use-foreman: true
            ruby: 2.7
          - repo: foreman-tasks
            org: theforeman
            use-foreman: true
            ruby: 2.7
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          path: ./projects/foreman-js
      - name: Checkout foreman
        if: ${{ matrix.use-foreman }}
        uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          path: ./projects/foreman
      - name: Checkout ${{ matrix.repo }}
        if: ${{ matrix.repo != 'foreman' }}
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.org }}/${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: ./projects/${{ matrix.repo }}
      - name: Set up plugin in Foreman
        run: |
          echo "gemspec name: '${{ matrix.repo }}', path: '${{ github.workspace }}/projects/${{ matrix.repo }}'" > "bundler.d/${{ matrix.repo }}.local.rb"
          if [ -d ${{ matrix.repo }}/gemfile.d ] ; then
            cat ${{ matrix.repo }}/gemfile.d/*.rb >> bundler.d/${{ matrix.repo }}.local.rb
          fi
        working-directory: ${{ github.workspace }}/projects/foreman
      - name: "Set up Ruby ${{ matrix.ruby }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ github.workspace }}/projects/foreman
      - name: Install foreman-js npm dependencies
        run: npm install --legacy-peer-deps
        working-directory: ${{ github.workspace }}/projects/foreman-js
      - name: Install foreman npm dependencies
        if: ${{ matrix.use-foreman }}
        run: npm install
        working-directory: ${{ github.workspace }}/projects/foreman
      - name: Install ${{ matrix.repo }} npm dependencies
        if: ${{ matrix.repo != 'foreman' }}
        run: npm install --legacy-peer-deps
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
      - name: Link foreman-js to foreman
        if: ${{ matrix.use-foreman }}
        run: npm run link -- --location '${{ github.workspace }}/projects/foreman'
        working-directory: ${{ github.workspace }}/projects/foreman-js
      - name: Link foreman-js to ${{ matrix.repo }}
        run: npm run link -- --location '${{ github.workspace }}/projects/${{ matrix.repo }}'
        working-directory: ${{ github.workspace }}/projects/foreman-js
      - name: Run ${{ matrix.repo }} tests
        run: npm run test:plugins ${{ matrix.repo }}
        working-directory: ${{ github.workspace }}/projects/foreman
      - name: Run ${{ matrix.repo }} lint
        run: npm run lint:plugins ${{ matrix.repo }}
        working-directory: ${{ github.workspace }}/projects/foreman
