name: foreman-js ci
on:
  pull_request:
    branches: [master]

jobs:
  test-with-plugins:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: katello
            org: Katello
            use-foreman: true
          - repo: foreman-tasks
            org: theforeman
            use-foreman: false
          - repo: foreman_rh_cloud
            org: theforeman
            use-foreman: false
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          path: ./projects/foreman-js
      - name: Checkout foreman
        if: ${{ matrix.use-foreman }}
        uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          path: ./projects/foreman
      - name: Checkout ${{ matrix.repo }}
        if: ${{ matrix.repo != 'foreman' }}
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.org }}/${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: ./projects/${{ matrix.repo }}
      - name: Install foreman-js npm dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/projects/foreman-js
      - name: Install foreman npm dependencies
        if: ${{ matrix.use-foreman }}
        run: npm install
        working-directory: ${{ github.workspace }}/projects/foreman
      - name: Install ${{ matrix.repo }} npm dependencies
        if: ${{ matrix.repo != 'foreman' }}
        run: npm install
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
      - name: Link foreman-js to foreman
        if: ${{ matrix.use-foreman }}
        run: npm run link -- --location '${{ github.workspace }}/projects/foreman'
        working-directory: ${{ github.workspace }}/projects/foreman-js
      - name: Link foreman-js to ${{ matrix.repo }}
        run: npm run link -- --location '${{ github.workspace }}/projects/${{ matrix.repo }}'
        working-directory: ${{ github.workspace }}/projects/foreman-js
      - name: Run ${{ matrix.repo }} tests
        run: npm test
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
      - name: Run ${{ matrix.repo }} lint
        run: npm run lint
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
